services:
  api:
    build:
      context: .
    container_name: fastapi-app
    environment:
      DATABASE_URL: "postgresql+psycopg2://kiruha:kiruha@postgres_db:5432/kiruha"
    ports:
      - '9090:80'
    restart: "no"
    depends_on:
      postgres_db:
        condition: service_started


  postgres_db:
    image: postgres
    restart: always
    ports:
      - 8988:5432
    environment:
      POSTGRES_PASSWORD: kiruha
      POSTGRES_USER: kiruha
    volumes:
      - "dbdata:/var/lib/postgresql/data"


  test_db:
    image: postgres
    restart: always
    ports:
      - 8987:5432
    environment:
      POSTGRES_PASSWORD: kiruha
      POSTGRES_USER: kiruha
    volumes:
      - "test_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8989:80
    environment:
      PGADMIN_DEFAULT_EMAIL: kiruha@kiruha.ru
      PGADMIN_DEFAULT_PASSWORD: kiruha


volumes:
  dbdata:
  test_data: