services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 8988:5432
    environment:
      POSTGRES_PASSWORD: kiruha
      POSTGRES_USER: kiruha
    volumes:
      - "dbdata:/var/lib/postgresql/data"


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8989:80
    environment:
      PGADMIN_DEFAULT_EMAIL: kiruha@kiruha.ru
      PGADMIN_DEFAULT_PASSWORD: kiruha


volumes:
  dbdata: